---
# Portworx Storage Class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-db-sc
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
parameters:
  repl: "3"
  io_profile: "db_remote"
  io_priority: "high"
  cow_ondemand: "false"
  disable_io_profile_protection: "1"
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: test
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      schedulerName: stork
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - postgresql-db
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgresql-db
          image: postgres:latest
          volumeMounts:
            - name: px-test-postgres
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: px-test-postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: portworx-db-sc
        resources:
          requests:
            storage: 2Gi
